version: '2.1'
services:
  cloud-config-server:
    image: "demo/cloud-config-server"
    environment:
      EUREKA_SERVER_NAME: ${EUREKA_SERVER_NAME}
      CONFIG_SERVER_NAME: ${CONFIG_SERVER_NAME}
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cloud-config-server:8082/actuator/health"]
      interval: 5s
      retries: 20

  cloud-gateway:
    image: "demo/cloud-gateway"
    environment:
      EUREKA_SERVER_NAME: ${EUREKA_SERVER_NAME}
      CONFIG_SERVER_NAME: ${CONFIG_SERVER_NAME}
    ports:
      - "8080:8080"
    links:
      - cloud-eureka-server
      - cloud-config-server
    depends_on:
      cloud-eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cloud-gateway:8080/actuator/health"]
      interval: 5s
      retries: 20

  cloud-eureka-server:
    image: "demo/cloud-eureka-server"
    environment:
      EUREKA_SERVER_NAME: ${EUREKA_SERVER_NAME}
      CONFIG_SERVER_NAME: ${CONFIG_SERVER_NAME}
    ports:
      - "8081:8081"
    links:
      - cloud-config-server
    depends_on:
      cloud-config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cloud-eureka-server:8081/actuator/health"]
      interval: 5s
      retries: 20

  cloud-hystrix-dashboard:
    image: "demo/cloud-hystrix-dashboard"
    environment:
      EUREKA_SERVER_NAME: ${EUREKA_SERVER_NAME}
      CONFIG_SERVER_NAME: ${CONFIG_SERVER_NAME}
    ports:
      - "8083:8083"
    links:
      - cloud-eureka-server
      - cloud-config-server
    depends_on:
      cloud-eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cloud-hystrix-dashboard:8083/actuator/health"]
      interval: 5s
      retries: 20

  core:
    image: "demo/core"
    environment:
      EUREKA_SERVER_NAME: ${EUREKA_SERVER_NAME}
      CONFIG_SERVER_NAME: ${CONFIG_SERVER_NAME}
    ports:
      - "8084:8084"
    links:
      - cloud-eureka-server
      - cloud-config-server
    depends_on:
      cloud-eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://core:8084/actuator/health"]
      interval: 5s
      retries: 20

