apiVersion: v1
kind: Service
metadata:
  name: cloud-config-server
  labels:
    run: cloud-config-server
spec:
  ports:
  - port: 8082
    protocol: TCP
  selector:
    run: cloud-config-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-server
spec:
  selector:
    matchLabels:
      run: cloud-config-server
  replicas: 1
  template:
    metadata:
      labels:
        run: cloud-config-server
    spec:
      containers:
      - name: cloud-config-server
        image: "${your-docker-hub-prefix}/cloud-config-server"
        ports:
        - containerPort: 8082
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 20
          periodSeconds: 20
        env:
        - name: EUREKA_SERVER_NAME
          value: "cloud-eureka-server"
        - name: CONFIG_SERVER_NAME
          value: "cloud-config-server"
      imagePullSecrets:
        - name: ${your-k8s-registry-key}

---

apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway
  labels:
    run: cloud-gateway
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: cloud-gateway

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway
spec:
  selector:
    matchLabels:
      run: cloud-gateway
  replicas: 1
  template:
    metadata:
      labels:
        run: cloud-gateway
    spec:
      containers:
      - name: cloud-gateway
        image: "${your-docker-hub-prefix}/cloud-gateway"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 20
        env:
        - name: EUREKA_SERVER_NAME
          value: "cloud-eureka-server"
        - name: CONFIG_SERVER_NAME
          value: "cloud-config-server"
      imagePullSecrets:
        - name: ${your-k8s-registry-key}

---

apiVersion: v1
kind: Service
metadata:
  name: cloud-eureka-server
  labels:
    run: cloud-eureka-server
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    run: cloud-eureka-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-eureka-server
spec:
  selector:
    matchLabels:
      run: cloud-eureka-server
  replicas: 1
  template:
    metadata:
      labels:
        run: cloud-eureka-server
    spec:
      containers:
      - name: cloud-eureka-server
        image: "${your-docker-hub-prefix}/cloud-eureka-server"
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 20
        env:
        - name: EUREKA_SERVER_NAME
          value: "cloud-eureka-server"
        - name: CONFIG_SERVER_NAME
          value: "cloud-config-server"
      imagePullSecrets:
        - name: ${your-k8s-registry-key}

---

apiVersion: v1
kind: Service
metadata:
  name: cloud-hystrix-dashboard
  labels:
    run: cloud-hystrix-dashboard
spec:
  ports:
  - port: 8083
    protocol: TCP
  selector:
    run: cloud-hystrix-dashboard

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-hystrix-dashboard
spec:
  selector:
    matchLabels:
      run: cloud-hystrix-dashboard
  replicas: 1
  template:
    metadata:
      labels:
        run: cloud-hystrix-dashboard
    spec:
      containers:
      - name: cloud-hystrix-dashboard
        image: "${your-docker-hub-prefix}/cloud-hystrix-dashboard"
        ports:
        - containerPort: 8083
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 20
          periodSeconds: 20
        env:
        - name: EUREKA_SERVER_NAME
          value: "cloud-eureka-server"
        - name: CONFIG_SERVER_NAME
          value: "cloud-config-server"
      imagePullSecrets:
        - name: ${your-k8s-registry-key}

---

apiVersion: v1
kind: Service
metadata:
  name: core
  labels:
    run: core
spec:
  ports:
  - port: 8084
    protocol: TCP
  selector:
    run: core

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
spec:
  selector:
    matchLabels:
      run: core
  replicas: 1
  template:
    metadata:
      labels:
        run: core
    spec:
      containers:
      - name: core
        image: "${your-docker-hub-prefix}/core"
        ports:
        - containerPort: 8084
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 20
          periodSeconds: 20
        env:
        - name: EUREKA_SERVER_NAME
          value: "cloud-eureka-server"
        - name: CONFIG_SERVER_NAME
          value: "cloud-config-server"
      imagePullSecrets:
        - name: ${your-k8s-registry-key}

---

