INSERT INTO VFS_CUSTOMER_SERVICE_CUSTOMER (Id, Name, Code) VALUES (1, 'Carrefour Libertad', 'CRF0001');
INSERT INTO VFS_CUSTOMER_SERVICE_CUSTOMER (Id, Name, Code) VALUES (2, 'Carrefour Rochester', 'CRF0002');
INSERT INTO VFS_CUSTOMER_SERVICE_CUSTOMER (Id, Name, Code) VALUES (3, 'Hipercor Bahía de Cádiz', 'HIP001');
INSERT INTO VFS_CUSTOMER_SERVICE_CUSTOMER (Id, Name, Code) VALUES (4, 'Carrefour Bahía Sur', 'CRF003');
INSERT INTO VFS_CUSTOMER_SERVICE_CUSTOMER (Id, Name, Code) VALUES (5, 'Supersol Estadio', 'SUP001');