INSERT INTO VFS_CUSTOMER_SERVICE_CUSTOMER (Name, Code) VALUES ('Carrefour Libertad', 'CRF0001');
INSERT INTO VFS_CUSTOMER_SERVICE_CUSTOMER (Name, Code) VALUES ('Carrefour Rochester', 'CRF0002');
INSERT INTO VFS_CUSTOMER_SERVICE_CUSTOMER (Name, Code) VALUES ('Hipercor Bahía de Cádiz', 'HIP001');
INSERT INTO VFS_CUSTOMER_SERVICE_CUSTOMER (Name, Code) VALUES ('Carrefour Bahía Sur', 'CRF003');
INSERT INTO VFS_CUSTOMER_SERVICE_CUSTOMER (Name, Code) VALUES ('Supersol Estadio', 'SUP001');